# Generated by Django 5.1.4 on 2026-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_whatsappcontact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='is_order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='order_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
