# Generated by Django 6.0.3 on 2026-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_enquiry_service_alter_enquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
