# Generated by Django 6.0.3 on 2026-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_enquiry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
