# Generated by Django 6.0.3 on 2026-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_order_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='order_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=20),
        ),
    ]
