# Generated by Django 5.1.4 on 2026-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_enquiry_is_order_confirmed_enquiry_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
