# Generated by Django 4.2.30 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_enquiry_status_alter_whatsappcontact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
