# Generated by Django 4.2.30 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_whatsappcontact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
