# Generated by Django 4.2.30 on 2026-05-04 07:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_makingvideo_youtube_url_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makingvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=products.models.MultiMediaCloudinaryStorage(), upload_to='making_videos/', validators=[products.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(storage=products.models.MultiMediaCloudinaryStorage(), upload_to='media_assets/', validators=[products.models.validate_file_size]),
        ),
    ]
